# Copyright (c) 2018 Ultimaker B.V.
# Cura is released under the terms of the LGPLv3 or higher.
from typing import Dict

from ...Models import BaseModel


## Class representing errors generated by the cloud servers, according to the json-api standard.
class CloudErrorObject(BaseModel):
    def __init__(self, **kwargs) -> None:
        self.id = None  # type: str
        self.code = None  # type: str
        self.http_status = None  # type: str
        self.title = None  # type: str
        self.detail = None  # type: str
        self.meta = None  # type: Dict[str, any]
        super().__init__(**kwargs)
