.TH CURA "1" "March 2017" "Cura" "User Commands"
.SH NAME
\fBCura \fP- Graphical user interface for the Cura slicing engine
.SH USAGE
cura
.SH DESCRIPTION
Cura prepares 3D models for 3D printing.
.PP
It is the main GUI client for the Cura slicing engine.
.PP
For novices, it makes it easy to get great results.
.PP
For experts, there are over 200 settings to adjust to your needs.
.PP
It doesn't take any command line arguments.
.SH AUTHOR
Cura is Copyright (c) 2015-2017 \fBUltimaker B.V.\fR
.PP
This man page was written by \fBGregor Riepl\fR <\&onitake@gmail\&.com\&>.