biome_types = {
    -1: "Will be computed",
    0: "Ocean",
    1: "Plains",
    2: "Desert",
    3: "Extreme Hills",
    4: "Forest",
    5: "Taiga",
    6: "Swampland",
    7: "River",
    8: "Hell",
    9: "Sky",
    10: "FrozenOcean",
    11: "FrozenRiver",
    12: "Ice Plains",
    13: "Ice Mountains",
    14: "MushroomIsland",
    15: "MushroomIslandShore",
    16: "Beach",
    17: "DesertHills",
    18: "ForestHills",
    19: "TaigaHills",
    20: "Extreme Hills Edge",
    21: "Jungle",
    22: "JungleHills",
}
