name: printer-linter-pr-diagnose

on:
  pull_request:
    paths:
      - "resources/**"

permissions:
  contents: read

jobs:
  printer-linter-diagnose:
    name: Printer linter PR diagnose

    runs-on: ubuntu-latest
    steps:
      - name: Setup the build environment
        uses: ultimaker/cura-workflows/.github/actions/setup-build-environment@main

      - id: get-diff
        uses: ultimaker/cura-workflows/.github/actions/get-diff@main
        with:
          files: |
            resources/extruders/*.def.json
            resources/definitions/*.def.json
            resources/intent/**/*.inst.cfg
            resources/quality/**/*.inst.cfg
            resources/variants/**/*.inst.cfg
          include_deleted: 'true'

      - name: Create results directory
        run: mkdir printer-linter-result

      - name: Diagnose file(s)
        if: steps.get-diff.outputs.files != ''
        run: python printer-linter/src/terminal.py --diagnose --report printer-linter-result/fixes.yml ${{ steps.get-diff.outputs.files_quoted }}

      - name: Check Deleted Files(s)
        if: steps.get-diff.outputs.files != ''
        run: python printer-linter/src/terminal.py --deleted --report printer-linter-result/comment.md ${{ steps.get-diff.outputs.files_quoted }}

      - name: Save PR metadata
        run: |
          echo ${{ github.event.number }} > printer-linter-result/pr-id.txt
          echo ${{ github.event.pull_request.head.repo.full_name }} > printer-linter-result/pr-head-repo.txt
          echo ${{ github.event.pull_request.head.sha }} > printer-linter-result/pr-head-sha.txt

      - uses: actions/upload-artifact@v7
        with:
          name: printer-linter-result
          path: printer-linter-result/
