name: unit-test

on:
  push:
    paths:
      - 'plugins/**'
      - 'resources/**'
      - 'cura/**'
      - 'icons/**'
      - 'tests/**'
      - '.github/workflows/unit-test.yml'
      - '.github/workflows/requirements-runner.txt'
      - 'requirements*.txt'
      - 'conanfile.py'
      - 'conandata.yml'
      - '*.jinja'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - '[0-9]+.[0-9]+'

  pull_request:
    paths:
      - 'plugins/**'
      - 'resources/**'
      - 'cura/**'
      - 'icons/**'
      - 'tests/**'
      - '.github/workflows/unit-test.yml'
      - '.github/workflows/requirements-runner.txt'
      - 'requirements*.txt'
      - 'conanfile.py'
      - 'conandata.yml'
      - '*.jinja'
    branches:
      - main
      - '[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  check_actor:
    uses: ultimaker/cura-workflows/.github/workflows/check-actor.yml@main
    secrets: inherit

  find-ticket-packages:
    name: Extract ticket and find packages
    uses: ultimaker/cura-workflows/.github/workflows/extract-ticket-and-find-packages.yml@main
    secrets: inherit

  testing:
    name: Run unit tests
    needs: [check_actor, find-ticket-packages]
    if: >-
      always() &&
      needs.check_actor.outputs.proceed == 'true' &&
      needs.find-ticket-packages.result == 'success'
    uses: ultimaker/cura-workflows/.github/workflows/unit-test.yml@main
    with:
      test_use_pytest: true
      package_overrides: ${{ needs.find-ticket-packages.outputs.package_overrides || '' }}
    secrets: inherit
